# Generated by Django 4.2.30 on 2026-09-05 00:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('start_id', models.PositiveIntegerField()),
                ('end_id', models.PositiveIntegerField()),
                ('chunks_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('created', 'Создана'), ('dispatched', 'Отправлена в Kafka'), ('in_progress', 'В процессе'), ('done', 'Завершена'), ('failed', 'Ошибка')], default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskChunk',
            fields=[
                ('chunk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('range_start', models.PositiveIntegerField()),
                ('range_end', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('dispatched', 'Отправлен'), ('in_progress', 'В процессе'), ('done', 'Завершён'), ('failed', 'Ошибка')], default='dispatched', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='tasks.downloadtask')),
            ],
            options={
                'ordering': ['range_start'],
            },
        ),
    ]
